### ISSUE TITLE
Decidir o banco de dados a ser utilizado

### ISSUE THREAD

**Issue by eufolim** [eufolim/Projeto-Final-DB2-SATC-2024#1]
O professor deixou que os grupos escolhessem o banco que preferem usar, 
porem o banco deve ser relacional.

Abri essa issue para decidirmos

**Comment by eufolim** [comment]
Estou mais acostumado com MySQL e SQLserver, mas se vocês são mais familiarizados com outro banco podemos usar

**Comment by JeanPrei** [comment]
acho o mysql melhor

**Comment by Alex-Farias** [comment]
MySQL tranquilo pra gente

**Comment by Ynd-Icaro** [comment]
MySql, atualmente pra gente.

**Comment by Araldi42** [comment]
Mysql ou postgres são bons
