### ISSUE TITLE
Alinhar com Professor Jorge sobre as 4 perguntas de regras de negócio

### ISSUE THREAD

**Issue by Alex-Farias** [eufolim/Projeto-Final-DB2-SATC-2024#10]
- Nas Instruções do Trabalho no AVA, são mencionadas as necessidades de regras de negócio com funcionalidades de ferramentas de banco que serão consideradas em 4 perguntas à escolha do professor referente ao trabalho final.

**Comment by jlsilva01** [comment]
@Alex-Farias nao precisa alinhar comigo as perguntas. 
Vocês mesmos podem criá-las com base em critérios que vocês mesmos deverão criar. 
Qualquer dúvida me avisem.

**Comment by Alex-Farias** [comment]
@jlsilva01 Perfeito, vou alinhar com os demais integrantes para levantarmos com o avanço das demais tarefas!

**Comment by Alex-Farias** [comment]
Possibilidade de perguntas
1 - Como obter a lista de vagas de estacionamento disponíveis e a quantidade de tempo que cada uma esteve disponível continuamente nos últimos 30 dias?;
2 - Qual a taxa de ocupação média de cada vaga de estacionamento por hora nos últimos 7 dias?;
3 - Quais as vagas de estacionamento que nunca ficaram disponíveis por mais de 4 horas consecutivas nos últimos 30 dias?;
4 - Quais os horários de pico de ocupação de vagas de estacionamento nos últimos 30 dias, considerando intervalos de 1 hora?.
