### ISSUE TITLE
Decidir linguagem para o CRUD

### ISSUE THREAD

**Issue by eufolim** [eufolim/Projeto-Final-DB2-SATC-2024#2]
O professor deixou que os grupos escolhessem a linguagem que preferem usar,
Ele recomendou focar no BackEnd e fazer o FrontEnd se sobrar tempo.

Abri essa issue para decidirmos.

**Comment by JeanPrei** [comment]
voto em python ou node.js

**Comment by Alex-Farias** [comment]
Python melhor escolha, mas node pode agilizar por já termos alguns scripts

**Comment by Ynd-Icaro** [comment]
Voto por node, utilizando Express.

**Comment by Araldi42** [comment]
Python
