### ISSUE TITLE
Atualização projeto

### ISSUE THREAD

**Issue by jlsilva01** [eufolim/Projeto-Final-DB2-SATC-2024#4]
@eufolim somente você efetuou atualização do repositório do trabalho até este momento.
Sugiro revalidarem a distribução das tarefas para que tenha commits frequentes neste repositório indicando o trabalho contínuo do mesmo de todos da equipe.
Dúvida, me avisem.

**Comment by Alex-Farias** [comment]
Após as entregas do dia 12/06/2024 estamos avaliando a distribuições de tarefas através da abertura de novas issues, portanto deverá ter novas definições até o próximo final de semana

**Comment by jlsilva01** [comment]
@Alex-Farias ok combinado!
